language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nan-webapp' ]; then cd .. && eval "mv $currentfolder generator-nan-webapp" && cd generator-nan-webapp; fi

